# Build customization
project_name: apkcompare
builds:
  - main: main.go
    binary: apkcompare
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS